-- MySQL Script generated by MySQL Workbench
-- jue 05 nov 2015 16:49:36 CLT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DB_INJUV_Backoffice
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `DB_INJUV_Backoffice` ;

-- -----------------------------------------------------
-- Schema DB_INJUV_Backoffice
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DB_INJUV_Backoffice` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `DB_INJUV_Backoffice` ;

-- -----------------------------------------------------
-- Table `Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `userName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  `fechaCreacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `admin` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `miembros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `miembros` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `miembros` (
  `id` VARCHAR(25) NOT NULL,
  `idTarea` VARCHAR(25) NOT NULL,
  `miembroscol` VARCHAR(45) NULL,
  `Usuario_id` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estado` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `estado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `value` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `adjuntos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adjuntos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `adjuntos` (
  `id` VARCHAR(25) NOT NULL,
  `idTarea` VARCHAR(25) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `extension` VARCHAR(45) NOT NULL,
  `fechaCreacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pioridad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pioridad` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pioridad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `color` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tareas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tareas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tareas` (
  `id` VARCHAR(22) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(140) NOT NULL,
  `idComentario` VARCHAR(25) NOT NULL,
  `fechaTermino` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `miembros_id` VARCHAR(25) NOT NULL,
  `estado_id` INT NOT NULL,
  `adjuntos_id` VARCHAR(25) NOT NULL,
  `pioridad_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `comentarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comentarios` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `comentarios` (
  `id` VARCHAR(25) NOT NULL,
  `idTarea` VARCHAR(25) NOT NULL,
  `fechaCreacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ultimaModificacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `comentarioscol` VARCHAR(45) NULL,
  `tareas_id` VARCHAR(22) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
